#!/usr/bin/env python3
"""Efficient, read-only Phase-B replay after Phase-A-negative.

Full-set AUD/OGL metrics are reused from the exact prior residual/mechanism
caches. Map replay is limited to fixed Group-A and three requested readouts
for quantities that were not cached previously.
"""
from pathlib import Path
import json, numpy as np, pandas as pd, torch
from run_audit import HERE, EXP, ROOT, XSA, RES, E80, EPS, phase_a, comp, desc, flatten, region_metrics, resize_norm, normalize

def main():
    for d in ['positive_map','satisfied_but_over','readout_comparison','visual_similarity','summary']:(HERE/d).mkdir(parents=True,exist_ok=True)
    v,dec=phase_a()
    if dec['phase_A']!='A-NEGATIVE':raise RuntimeError(dec)
    # Exact full-set AUD/OGL metrics already generated by the frozen residual audit.
    obj=pd.read_csv(XSA/'mechanism/object_per_sample_all.csv');obj=obj[(obj.scale.eq('144k'))&(obj.dataset.eq('vggss'))&(obj.model.eq('mean'))][['sample_id','background_response','fp_area_ratio']]
    audit=v.merge(obj,on='sample_id',validate='one_to_one')
    audit['gt_response']=audit.aud_gt_response;audit['nearfp_response']=audit.aud_nearfp_response;audit['gt_nearfp_gap']=audit.aud_gap;audit['gt_nearfp_auroc']=audit.aud_auroc;audit['precision']=audit.aud_precision;audit['coverage']=audit.aud_coverage;audit['activated_area']=audit.aud_area;audit['entropy']=audit.aud_entropy
    # ``fp_area_ratio`` is the existing thresholded outside-GT activation
    # measure; retain it rather than redefining an unvalidated mass score.
    audit['outside_inside_activation_ratio']=audit.fp_area_ratio/np.maximum(audit.gt_area_ratio,EPS)
    audit.to_csv(HERE/'positive_map/per_sample_positive_metrics.csv',index=False)
    a=audit.group.eq('A_ogl_help')
    metrics=['gt_response','nearfp_response','background_response','gt_nearfp_gap','gt_nearfp_auroc','precision','coverage','activated_area','entropy','fp_area_ratio','outside_inside_activation_ratio']
    gp={m:comp(audit.loc[a,m],audit.loc[~a,m],f'positive:{m}') for m in metrics}
    pd.DataFrame(flatten('fixed Group-A vs non-Group-A positive AUD map',gp)).to_csv(HERE/'positive_map/groupA_positive_summary.csv',index=False)
    # Exact OGL correction values from the prior AUD-vs-OGL paired audit.
    td=audit.loc[a,['sample_id','sample_index','AddTP','AddFP','RemoveTP','RemoveFP','aud_gt_response','aud_nearfp_response','aud_area','ogl_gt_response','ogl_nearfp_response','ogl_area']].copy()
    td['ogl_minus_aud_gt_response']=td.ogl_gt_response-td.aud_gt_response;td['ogl_minus_aud_nearfp_response']=td.ogl_nearfp_response-td.aud_nearfp_response;td['ogl_minus_aud_area']=td.ogl_area-td.aud_area
    td.to_csv(HERE/'positive_map/ogl_correction_per_sample.csv',index=False)
    pd.DataFrame([{'metric':m,**desc(td[m],f'ogl:{m}')} for m in ['ogl_minus_aud_gt_response','ogl_minus_aud_nearfp_response','ogl_minus_aud_area','RemoveFP','RemoveTP','AddTP','AddFP']]).to_csv(HERE/'positive_map/groupA_ogl_correction_summary.csv',index=False)
    audit['constraint_state']=np.where(audit.margin>0,'satisfied','violated');audit['spatial_state']=np.where(audit.auto_taxonomy.eq('OVER'),'over_activated','not_over')
    four=audit.groupby(['constraint_state','spatial_state']).agg(n=('sample_id','size'),groupA_n=('group',lambda z:int((z=='A_ogl_help').sum()),),groupA_fraction=('group',lambda z:float((z=='A_ogl_help').mean())),mean_ogl_minus_aud=('delta_iou','mean'),precision=('precision','mean'),coverage=('coverage','mean'),activated_area=('activated_area','mean')).reset_index();four.to_csv(HERE/'satisfied_but_over/four_way_partition.csv',index=False)
    # Replay only Group-A AUD/IMG_QUERY/IQR maps for requested readout-region
    # metrics. This does not touch the model; inputs are immutable cache files.
    maps=np.load(EXP/'mechanism_audit/results/vggss/full/cram_c3_stage2_maps.npz',allow_pickle=False);nat=np.load(EXP/'natural_localization/vggss/C3/seed12345/natural_maps.npz',allow_pickle=False);fixed=np.load(E80/'results/vggss_144k_sample_indices.npz',allow_pickle=False);ids=maps['ids'].astype(str);assert np.array_equal(ids,nat['ids'].astype(str))
    index_by={sid:i for i,sid in enumerate(ids)};inds=np.array([index_by[s] for s in audit.loc[a,'sample_id']],int);device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu');read=[]
    for st in range(0,len(inds),64):
        ii=inds[st:st+64];aud=resize_norm(maps['H_matched'][ii],device);img=resize_norm(nat['image_native'][ii].reshape(len(ii),49),device);iqr=normalize(torch.from_numpy(.6*aud+.4*img)).numpy()
        for local,i in enumerate(ii):
            for name,score in [('AUD',aud[local]),('IMG_QUERY',img[local]),('IQR',iqr[local])]:read.append({'sample_id':ids[i],'sample_index':int(i),'readout':name,**region_metrics(score,nat['gt_masks'],fixed,int(i),False)})
    rr=pd.DataFrame(read);rr.to_csv(HERE/'readout_comparison/aud_img_iqr_groupA_per_sample.csv',index=False);rr.groupby('readout').mean(numeric_only=True).reset_index().to_csv(HERE/'readout_comparison/aud_img_iqr_groupA.csv',index=False)
    # Existing C3 visual-key cache, descriptive only.
    keys=np.load(EXP/'natural_localization/vggss/C3/seed12345/visual_keys.npy',mmap_mode='r');gt=nat['gt_masks'];sim=[]
    for i in range(len(ids)):
        g7=gt[i].reshape(7,32,7,32).mean((1,3)).reshape(49);near=np.zeros(224*224,float);ni=fixed['indices'][i,2,:int(fixed['counts'][i,2])];near[ni]=1;n7=near.reshape(7,32,7,32).mean((1,3)).reshape(49);gv=(keys[i]*g7[:,None]).sum(0)/max(g7.sum(),EPS);nv=(keys[i]*n7[:,None]).sum(0)/max(n7.sum(),EPS);sim.append({'sample_id':ids[i],'sample_index':i,'gt_nearfp_visual_cosine':float(np.dot(gv,nv)/max(np.linalg.norm(gv)*np.linalg.norm(nv),EPS))})
    sim=pd.DataFrame(sim).merge(audit[['sample_id','group']],on='sample_id',validate='one_to_one');sim.to_csv(HERE/'visual_similarity/gt_nearfp_feature_similarity.csv',index=False);z=comp(sim.loc[sim.group.eq('A_ogl_help'),'gt_nearfp_visual_cosine'],sim.loc[~sim.group.eq('A_ogl_help'),'gt_nearfp_visual_cosine'],'visual');pd.DataFrame(flatten('fixed Group-A vs non-Group-A C3 visual cosine',{'gt_nearfp_visual_cosine':z})).to_csv(HERE/'visual_similarity/groupA_visual_similarity_summary.csv',index=False)
    (HERE/'summary/analysis_bundle.json').write_text(json.dumps({'phase_A':dec,'phase_B':'completed_cached_replay','visual_similarity':z},indent=2));print(json.dumps(dec,indent=2))
if __name__=='__main__':main()
